name: flutter_server
description: Geopaparazzi Survey Server.

version: 4.3.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  ###########################
  # OWN
  ###########################

  smashlibs:
    path: ./smashlibs/
    # git:
    #   url: https://github.com/moovida/smashlibs.git
      # ref: e08e258

  dart_hydrologis_utils: ^0.8.1

  dart_jts: ^0.2.3

  ###########################
  # OTHERS
  ############################

  # BSD
  http: ^0.13.5

  # MIT
  horizontal_data_table: ^4.1.2+2

  # MIT
  after_layout: ^1.2.0

  # MIT
  material_design_icons_flutter: ^7.0.7296

  # Apache 2.0
  # charts_flutter: ^0.12.0

  # MIT
  provider: ^6.0.3

  # apache
  latlong2: ^0.8.1

  # MIT
  flutter_tags_x: ^1.1.0

  # BSD
  flutter_map: ^4.0.0
    # git:
    #   url: https://github.com/moovida/flutter_map.git
    #   ref: version4smash
  
  # BSD
  flutter_map_marker_cluster: ^1.1.1
    # git:
    #   url: https://github.com/moovida/flutter_map_marker_cluster.git
    #   ref: version4smash

  # GPL3
  # flutter_map_tappable_polyline: ^3.2.0

  # MIT
  transparent_image: ^2.0.0

dev_dependencies:
  test: ^1.20.1

  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/smash_logo.png
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
